name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # ...existing code...
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "3.2.2"
      #     bundler-cache: true
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ./.docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: my-ruby-app:latest
          cache-from: type=local,mode=max,src=./.docker-cache
          cache-to: type=local,modedest=./.docker-cache
          # cache-from: type=gha,mode=max
          # cache-to: type=gha,mode=max


# i was also reflecting over how i left in the morning. 
# I may have come across a bit cold, which wasn't  