name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache vendor directory
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name : create vendor directory
        run: |
          mkdir -p vendor

      - name: Build image with Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: mehdizonjy/ruby-cache-test
          tags: latest ${{ github.sha }}
          layers: true
          containerfiles: |
            ./Dockerfile
          context: .
          extra-args: |
            --ssh default
            --cache-to=mehdizonjy/ruby-cache-test
            --cache-from=mehdizonjy/ruby-cache-test