name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vendor directory
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # - name: Set up Ruby for local bundle
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "3.2.2"
      #     bundler-cache: false

      # - name: Install dependencies locally to populate vendor
      #   run: |
      #     bundle config set --local path 'vendor'
      #     bundle install --jobs $(nproc) --retry 3

 
      - name: Build image with Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-ruby-app
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          context: .